### ISSUE TITLE
Content-Type を設定してほしい

### ISSUE THREAD

**Issue by tokuhirom** [org-mode-doc-ja/org-ja#728]
http://orgmode.jp/doc-ja/org-ja.html
このページなのですが、content-type の指定がないために一部ブラウザで文字化けしてしまうようです。具体的には iphone の safari で文字化けしています。
meta タグか http header で charset を指定していただけるとありがたいです。

**Comment by takaxp** [comment]
https://takaxp.github.io/org-ja.html に charset を明示したものを置きました．どうでしょう．
というか，何年も放置して申し訳ないです．
